name: movie_list_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  board_datetime_picker: ^2.8.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_web_plugins:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^16.0.0
  go_transitions: ^0.8.2
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  logger: ^2.6.0
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app-icon-1024x1024.png"
  adaptive_icon_foreground_inset: 24 # default: 16
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  color_dark: "#000000"
  # background_image: "assets/icons/native_splash/background.png"
  # background_image_dark: "assets/icons/native_splash/background.png"
  image: "assets/icons/native_splash/logo.png"
  image_dark: "assets/icons/native_splash/logo.png"
  branding: "assets/icons/native_splash/branding.png"
  branding_dark: "assets/icons/native_splash/branding.png"
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: "assets/icons/native_splash/android_12_and_above/logo_android_12.png"
    # image: "assets/icons/native_splash/android_12_and_above/backgorund_android_12.png"
    image_dark: "assets/icons/native_splash/android_12_and_above/logo_android_12.png"
    # image_dark: "assets/icons/native_splash/android_12_and_above/backgorund_android_12.png"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"
    branding: "assets/icons/native_splash/android_12_and_above/branding_android_12.png"
  # command: dart run flutter_native_splash:create
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/icons/
    - assets/icons/native_splash/
    - assets/icons/native_splash/android_12_and_above/
    - assets/images/
    - assets/json/
    - assets/lottie/
    - assets/svgs/

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Urbanist
      fonts:
        # Extra Heavy Bold
        - asset: assets/fonts/Urbanist-ExtraHeavyBold.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-ExtraHeavyBoldItalic.ttf
          weight: 900
          style: italic
        # Extra Bold
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        # Bold
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        # Semi Bold
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Medium
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        # Regular
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-RegularItalic.ttf
          weight: 400
          style: italic
        # Light
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        # Extra Light
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        # Thin
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
